### ISSUE TITLE
Documentation and Contributions

### ISSUE THREAD

**Issue by trojanc** [jandrassy/arduino-firmware-wifilink#5]
Hi

Firstly, thank you for this fork!

I would like to contribute (or fork another) some code for this project, but I'm a bit confused as to what branch I should be looking at. The ota and master branches seem to be somewhat distant from each other. What is the ota branch?

My plans are (using Arduino Uno Wifi Developer Edition)

1. Making the builds platformio compatible
2. Add MQTT to the ESP side (atmega can just push data to esp which will send it to mqtt)
3. Support OTA updates for both the ESP and Arduino
4. Upload firmware (.bin files) from a web page
5. Password protect the web page
6. Tag the code more often to keep track of which versions are compatible with each other (firmware and library side of things)
... got some more ideas, but this is mainly what I would like to make possible...

**Comment by JAndrassy** [comment]
Hi. arduino.org has ota support only in the ota branch. I moved it to master (not by merging, only cherry-piking). But I can not delete the branch because there was my first documentation for Uno WiFi and WiFi Link and the links to it are over the Internet.

The build and upload of WiFi Link firmware is a one time thing for the end user. It can be done with Arduino IDE, I think, there is no need to complicate it with platformio.

If someone wants the esp-link way of MQTT access, esp-link can be installed on Uno WiFi Dev Ed.  With WiFi Link library, the PubSubClient  library can be used over WiFiClent to access MQTT server.

OTA is supported. What do you want to add to it?

I do not use Uno WiFi and WiFi Link anymore, so I would not accepts PR, because I have no time to test it. I can add a link to readme, pointing to your fork. 

The WiFi Link firmware and library are so bad coded, that I gave up fixing it. The bigest problem is that data of concurrent WiFiClients are mixed up.
